### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by avitase** [PacktPublishing/Mastering-Reinforcement-Learning-with-Python#3]
The [link for suggestions and feedback](https://github.com/PacktPublishing/Mastering-Reinforcement-Learning-with-Python/blob/004bbe28b467bb273ec4578d6926403525f517b2/README.md?plain=1#L74) is broken.

**Comment by JosephA-packt** [comment]
For suggestions and feedback you have to send an email at customercare@packtpub.com . No link in the book is broken. If you still have an issue with the link that your talking about please mention to us the page where you found the broken link.
